### PR TITLE
fix known bugs

### PR DESCRIPTION
**Pull request by kolharsam**

### CODE REVIEW

**Comment by kolharsam** [comment]
@beerose don't merge this yet, there's one small issue I spotted, fixing that atm.

The issue is just that once the relationship is removed, it isn't part of the untrackedRelations....so yeah, fixing that

**Comment by kolharsam** [comment]
I think it's ready for merge now

**Comment by beerose** [comment]
Turns out it was just a wrong property access bug. Fixed here: https://github.com/hasura/graphql-engine/pull/5654/commits/d3b270cf1f0ac0d166b8899313b3eb01f90a8385

**Comment by kolharsam** [comment]
Yes. But this was the case with the one that you reported. The other bug was with relationships shown on the `Schema` page

**Comment by beerose** [comment]
Fixed both issues for me.

**Pull request closed without merging**
